openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
tags:
  -
    name: Endpoints
    description: ''
paths:
  /api/up:
    get:
      summary: ''
      operationId: getApiUp
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: ok
                properties:
                  status:
                    type: string
                    example: ok
      tags:
        - Endpoints
      security: []
  /api/products:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: Pen
                      category_id: 1
                      status: published
                      created_at: '2025-03-10T13:28:38.000000Z'
                      updated_at: '2025-03-10T13:28:38.000000Z'
                      deleted_at: null
                    -
                      id: 2
                      name: Bread
                      category_id: 2
                      status: draft
                      created_at: '2025-03-10T13:31:17.000000Z'
                      updated_at: '2025-03-10T13:31:17.000000Z'
                      deleted_at: null
                    -
                      id: 4
                      name: 'Quincy Stokes'
                      category_id: 3
                      status: published
                      created_at: '2025-03-10T14:06:42.000000Z'
                      updated_at: '2025-03-10T14:06:42.000000Z'
                      deleted_at: null
                    -
                      id: 5
                      name: 'Mr. Eladio Stehr'
                      category_id: 4
                      status: draft
                      created_at: '2025-03-10T14:06:42.000000Z'
                      updated_at: '2025-03-10T14:06:42.000000Z'
                      deleted_at: null
                    -
                      id: 6
                      name: 'Alejandra Schaefer'
                      category_id: 5
                      status: draft
                      created_at: '2025-03-10T14:06:42.000000Z'
                      updated_at: '2025-03-10T14:06:42.000000Z'
                      deleted_at: null
                    -
                      id: 7
                      name: 'Dovie Breitenberg'
                      category_id: 6
                      status: published
                      created_at: '2025-03-10T14:06:42.000000Z'
                      updated_at: '2025-03-10T14:06:42.000000Z'
                      deleted_at: null
                    -
                      id: 8
                      name: 'Darian Christiansen'
                      category_id: 7
                      status: published
                      created_at: '2025-03-10T14:06:42.000000Z'
                      updated_at: '2025-03-10T14:06:42.000000Z'
                      deleted_at: null
                    -
                      id: 9
                      name: 'Kristin Ward'
                      category_id: 8
                      status: draft
                      created_at: '2025-03-10T14:06:42.000000Z'
                      updated_at: '2025-03-10T14:06:42.000000Z'
                      deleted_at: null
                    -
                      id: 10
                      name: 'Kameron Mraz II'
                      category_id: 9
                      status: draft
                      created_at: '2025-03-10T14:06:42.000000Z'
                      updated_at: '2025-03-10T14:06:42.000000Z'
                      deleted_at: null
                    -
                      id: 11
                      name: 'Prof. Fred Ankunding'
                      category_id: 10
                      status: draft
                      created_at: '2025-03-10T14:06:42.000000Z'
                      updated_at: '2025-03-10T14:06:42.000000Z'
                      deleted_at: null
                  links:
                    first: 'http://localhost:8000/api/products?page=1'
                    last: 'http://localhost:8000/api/products?page=2'
                    prev: null
                    next: 'http://localhost:8000/api/products?page=2'
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 2
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost:8000/api/products?page=1'
                        label: '1'
                        active: true
                      -
                        url: 'http://localhost:8000/api/products?page=2'
                        label: '2'
                        active: false
                      -
                        url: 'http://localhost:8000/api/products?page=2'
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost:8000/api/products'
                    per_page: 10
                    to: 10
                    total: 12
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: Pen
                        category_id: 1
                        status: published
                        created_at: '2025-03-10T13:28:38.000000Z'
                        updated_at: '2025-03-10T13:28:38.000000Z'
                        deleted_at: null
                      -
                        id: 2
                        name: Bread
                        category_id: 2
                        status: draft
                        created_at: '2025-03-10T13:31:17.000000Z'
                        updated_at: '2025-03-10T13:31:17.000000Z'
                        deleted_at: null
                      -
                        id: 4
                        name: 'Quincy Stokes'
                        category_id: 3
                        status: published
                        created_at: '2025-03-10T14:06:42.000000Z'
                        updated_at: '2025-03-10T14:06:42.000000Z'
                        deleted_at: null
                      -
                        id: 5
                        name: 'Mr. Eladio Stehr'
                        category_id: 4
                        status: draft
                        created_at: '2025-03-10T14:06:42.000000Z'
                        updated_at: '2025-03-10T14:06:42.000000Z'
                        deleted_at: null
                      -
                        id: 6
                        name: 'Alejandra Schaefer'
                        category_id: 5
                        status: draft
                        created_at: '2025-03-10T14:06:42.000000Z'
                        updated_at: '2025-03-10T14:06:42.000000Z'
                        deleted_at: null
                      -
                        id: 7
                        name: 'Dovie Breitenberg'
                        category_id: 6
                        status: published
                        created_at: '2025-03-10T14:06:42.000000Z'
                        updated_at: '2025-03-10T14:06:42.000000Z'
                        deleted_at: null
                      -
                        id: 8
                        name: 'Darian Christiansen'
                        category_id: 7
                        status: published
                        created_at: '2025-03-10T14:06:42.000000Z'
                        updated_at: '2025-03-10T14:06:42.000000Z'
                        deleted_at: null
                      -
                        id: 9
                        name: 'Kristin Ward'
                        category_id: 8
                        status: draft
                        created_at: '2025-03-10T14:06:42.000000Z'
                        updated_at: '2025-03-10T14:06:42.000000Z'
                        deleted_at: null
                      -
                        id: 10
                        name: 'Kameron Mraz II'
                        category_id: 9
                        status: draft
                        created_at: '2025-03-10T14:06:42.000000Z'
                        updated_at: '2025-03-10T14:06:42.000000Z'
                        deleted_at: null
                      -
                        id: 11
                        name: 'Prof. Fred Ankunding'
                        category_id: 10
                        status: draft
                        created_at: '2025-03-10T14:06:42.000000Z'
                        updated_at: '2025-03-10T14:06:42.000000Z'
                        deleted_at: null
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Pen
                        category_id:
                          type: integer
                          example: 1
                        status:
                          type: string
                          example: published
                        created_at:
                          type: string
                          example: '2025-03-10T13:28:38.000000Z'
                        updated_at:
                          type: string
                          example: '2025-03-10T13:28:38.000000Z'
                        deleted_at:
                          type: string
                          example: null
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost:8000/api/products?page=1'
                      last:
                        type: string
                        example: 'http://localhost:8000/api/products?page=2'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: 'http://localhost:8000/api/products?page=2'
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 2
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost:8000/api/products?page=1'
                            label: '1'
                            active: true
                          -
                            url: 'http://localhost:8000/api/products?page=2'
                            label: '2'
                            active: false
                          -
                            url: 'http://localhost:8000/api/products?page=2'
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost:8000/api/products'
                      per_page:
                        type: integer
                        example: 10
                      to:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 12
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: b
                  nullable: false
                category_id:
                  type: number
                  description: 'The <code>id</code> of an existing record in the categories table. Must not be greater than 255.'
                  example: 22
                  nullable: false
                status:
                  type: string
                  description: ''
                  example: draft
                  nullable: false
                  enum:
                    - draft
                    - published
              required:
                - name
                - category_id
                - status
      security: []
  '/api/products/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    name: Pen
                    category_id: 1
                    status: published
                    created_at: '2025-03-10T13:28:38.000000Z'
                    updated_at: '2025-03-10T13:28:38.000000Z'
                    deleted_at: null
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Pen
                      category_id:
                        type: integer
                        example: 1
                      status:
                        type: string
                        example: published
                      created_at:
                        type: string
                        example: '2025-03-10T13:28:38.000000Z'
                      updated_at:
                        type: string
                        example: '2025-03-10T13:28:38.000000Z'
                      deleted_at:
                        type: string
                        example: null
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
